fn main {
  // Decimal number
  let num1 = 1000
  println(num1)

  // Allow underscores in numbers, same as 100000000 
  let num2 = 100_000_000 
  println(num2)

  // Hexadecimal number, same as 65535
  let num3 = 0xFFFF 
  println(num3)

  // Binary number, same as 9
  let num4 = 0b1001 
  println(num4)

  // Double precision floating point  
  let _num5 : Double = 3.14 
  
  // Unsigned integer with 32 bits and 64 bits
  let _unsigned32 : UInt = 1000
  let _unsigned64 : UInt64 = 1000
}

