name: check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 10 * * 2'

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          /bin/bash -c "$(curl -fsSL https://cli.moonbitlang.com/ubuntu_x86_64_moon_setup.sh)"
          echo "/home/runner/.moon/bin" >> $GITHUB_PATH

      - name: check single file
        run: |
          find . -maxdepth 1 -type f -name '*.mbt' | \
          while read -r file; do
            moonc check "$file" -std-path ~/.moon/lib/core/target/bundle || exit 1
          done
